name: Deploy to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env

      - name: Build Project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete --exclude ".git/*"

      - name: Invalidate CloudFront
        env:
          DIST_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          if [ -n "$DIST_ID" ]; then
            echo "Invalidating CloudFront distribution..."
            aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"
          else
            echo "Skipping CloudFront invalidation (DIST_ID is empty)."
          fi
